INCLUDE Global.ink

Hi {player_Name} I see you're collecting Heat Sinks. Want to know more about it? #speaker: Luke #portrait: 26

    * Yes #speaker: {player_Name} #portrait: 0
        In order to gather the materials here which is the Heat Sink, you need to defeat the enemies here. #speaker: Luke #portrait: 26
        The Heat Sink of a CPU fan is primarily made from materials that are excellent at conducting heat. #speaker: Luke #portrait: 26
        These materials help absorb and disperse the heat generated by the CPU into the surrounding air, which the fan then expels. #speaker: Luke #portrait: 26
        Materials of the Heat Sink can be either Aluminum, Copper, or a combination of both. #speaker: Luke #portrait: 26
        Aluminum and copper are the two dominant materials, with copper used for its superior heat transfer capabilities and aluminum for its lightweight and cost-effective properties. #speaker: Luke #portrait: 26
        That is all. #speaker: Luke #portrait: 26
        I like those options #speaker: {player_Name} #portrait: 0
        I also approve these options as you can opt out to either a cost-effective or to a more expensive yet superior Heat Sink to the other. #speaker: Luke #portrait: 26
        Anyway, I appreciate you listening to me about Heat Sink. Be safe mate. #speaker: Luke #portrait: 26

     * No #speaker: {player_Name} #portrait: 0
        Anyway, be safe mate. #speaker: Luke #portrait: 26
